FROM gliderlabs/alpine

ENV HUGO_VERSION 0.54.0
MAINTAINER koenigphil@gmail.com

# Install HUGO
RUN set -x && \
  apk add --update wget ca-certificates && \
  wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz && \
  tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C /usr/bin && \
  rm -r hugo_${HUGO_VERSION}_Linux-64bit.tar.gz && \
  apk del wget ca-certificates && \
  rm /var/cache/apk/*

ENTRYPOINT ["/usr/bin/hugo"]
